### Listar GET
GET http://localhost:3000/producto

### Crear POST
POST http://localhost:3000/producto
Content-Type: application/json

{
  "nombre": "mouse",
  "estado": true
}

### Mostrar GET
GET http://localhost:3000/producto/3

### Modificar PUT
PUT http://localhost:3000/producto/34

### Eliminar DELETE
DELETE http://localhost:3000/producto/34